services:
  caddy:
    image: caddy-cloudflare:latest  # 👈 Use the image you just built
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/wassim/Documents/Local_Services/Chatwoot/aquaworld:/srv/aquaworld
    env_file:
      - ./caddy.env
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true