name: mariadb
services:
  database:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    container_name: mariadb-database
    environment:
      MYSQL_ROOT_PASSWORD: Wassim1986
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost --password=Wassim1986
      interval: 1s
      retries: 20
    image: mariadb:10.6
    networks:
      mariadb-network: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/ubuntu/OpsSync/OpsSync_DataBase
        target: /var/lib/mysql
networks:
  mariadb-network:
    name: mariadb-network