name: opssync1
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

    restart: unless-stopped
  configurator:
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      redis-cache:
        condition: service_started
        required: true
      redis-queue:
        condition: service_started
        required: true
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: mariadb-database
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
        required: true
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      traefik-public: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

    restart: unless-stopped
  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

    restart: unless-stopped
  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

    restart: unless-stopped
  redis-cache:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    restart: unless-stopped
  redis-queue:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}
    restart: unless-stopped
  scheduler:
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

    restart: unless-stopped
  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: ghcr.io/wkoubaa1986/opssync:3.0.1
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: never
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached

    restart: unless-stopped
  backup:
    image: backup-image:2.0.0
    entrypoint: ["bash", "-c", "/usr/local/bin/backup-and-schedule.sh"]
    environment:
      DB_HOST: mariadb-database
      DB_PASSWORD: ${DB_PASSWORD}
      BACKUP_CRON_SCHEDULE: "0 */6 * * *"
      MANUAL_BACKUP: "false"  # Run backup immediately when container starts
    volumes:
      - /home/wassim/Documents/Local_Services/OpsSync/sites:/home/frappe/frappe-bench/sites:cached
      - /home/wassim/Documents/Local_Services/OpsSync/OpsSync_Backup:/external-backup:rw
    networks:
      bench-network: null
      mariadb-network: null
    restart: on-failure
networks:
  bench-network:
    name: opssync1
  mariadb-network:
    name: mariadb-network
    external: true
  traefik-public:
    name: traefik-public
    external: true
volumes:
  redis-queue-data:
    name: opssync1_redis-queue-data

# x-backend-defaults:
#   depends_on:
#     configurator:
#       condition: service_completed_successfully
#   image: ghcr.io/wkoubaa1986/opssync:3.0.1
#   pull_policy: never
#   volumes:
#     - sites:/home/frappe/frappe-bench/sites
# x-customizable-image:
#   image: ghcr.io/wkoubaa1986/opssync:3.0.1
#   pull_policy: never
# x-depends-on-configurator:
#   depends_on:
#     configurator:
#       condition: service_completed_successfully
